---
title: "Código Dashboard"
Author: "Clàudia Hernández"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
  runtime: shiny
  
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(maps)
library(DT)
library(lorem)
library(ggplot2)
library(dplyr)
library(plotly)
library(mapdata)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)

```

```{r}
datos <- read.csv("datosr2_depurado.csv", header=TRUE, sep=",")
```

```{r}

```

Gráficos {data-icon=fa-signal}
=========================================
Column {data-width=450}
-----------------------------------------------------------------------

### Casos de discriminación (2002-2023)

```{r}
#Filtro los datos porque la información sobre las personas no discriminadas no es interesante para el objetivo
datos$essround <- as.factor(datos$essround)
datos$discrimination <- as.factor(datos$discrimination)

datos_filtrados <- datos %>% filter(discrimination != "No discriminado")

#Cuento el número de casos por año y tipo de discriminación
datos_agg <- datos_filtrados %>%
  group_by(essround, discrimination) %>%
  summarise(count = n())

#Me aseguro de que ess round sea numérico para el gráfico de serie temporal
datos_agg$essround <- as.numeric(as.character(datos_agg$essround))

# Crear el gráfico de serie temporal
p <-ggplot(data = datos_agg, aes(x = essround, y = count, color = discrimination, group = discrimination)) +
  geom_line() +
  geom_point() +
  labs(title = "Evolución temporal de los casos de discriminación por tipo",
       x = "Año",
       y = "Número de casos",
       color = "Tipo de discriminación") +
  theme_minimal()

#Añado la interacción
p_interactive <- ggplotly(p) %>% 
  layout(legend = list(title = list(text = 'Tipo de discriminación')))

# Muestro el gráfico
p_interactive

```

Column {data-width=550}
-----------------------------------------------------------------------

### Discriminación por región

```{r fig.width=16, fig.height=10}
spain_map <- ne_states(country = "Spain", returnclass = "sf")


datos_filtrados_con_comunidad <- datos_filtrados %>%
  filter(!is.na(region) & region != "")

frecuencia_discriminacion <- datos_filtrados_con_comunidad %>%
  group_by(region) %>%
  summarise(casos = n())

codigos_a_nombres <- c(
  ES11 = "Galicia", 
  ES12 = "Principado de Asturias", 
  ES13 = "Cantabria", 
  ES21 = "País Vasco", 
  ES22 = "Comunidad Foral de Navarra", 
  ES23 = "La Rioja", 
  ES24 = "Aragón", 
  ES30 = "Comunidad de Madrid", 
  ES41 = "Castilla y León", 
  ES42 = "Castilla-La Mancha", 
  ES43 = "Extremadura", 
  ES51 = "Cataluña", 
  ES52 = "Comunitat Valenciana", 
  ES53 = "Illes Balears", 
  ES61 = "Andalucía", 
  ES62 = "Región de Murcia", 
  ES63 = "Ciudad de Ceuta", 
  ES64 = "Ciudad de Melilla", 
  ES70 = "Canarias"
)

frecuencia_discriminacion <- frecuencia_discriminacion %>% 
  mutate(region = codigos_a_nombres[region])

nombres_nuevos <- c(
  "Ciudad de Ceuta" = "Ceuta",
  "Ciudad de Melilla" = "Melilla",
  "Comunidad Foral de Navarra" = "Foral de Navarra",
  "País Vasco" = "País Vasco",
  "Aragón" = "Aragón",
  "Cataluña" = "Cataluña",
  "Extremadura" = "Extremadura",
  "Andalucía" = "Andalucía",
  "Galicia" = "Galicia",
  "Castilla y León" = "Castilla y León",
  "Comunitat Valenciana" = "Valenciana",
  "Región de Murcia" = "Murcia",
  "Principado de Asturias" = "Asturias",
  "Cantabria" = "Cantabria",
  "Canarias" = "Canary Is.",
  "Illes Balears" = "Islas Baleares",
  "La Rioja" = "La Rioja",
  "Castilla-La Mancha" = "Castilla-La Mancha",
  "Comunidad de Madrid" = "Madrid"
)


frecuencia_discriminacion <- frecuencia_discriminacion %>%
  mutate(region = nombres_nuevos[region])

poblacion_comunidades <- tibble::tibble(
  region = c("Galicia", "Asturias", "Cantabria", "País Vasco", "Foral de Navarra", 
             "La Rioja", "Aragón", "Madrid", "Castilla y León", "Castilla-La Mancha", 
             "Extremadura", "Cataluña", "Valenciana", "Islas Baleares", "Andalucía", 
             "Murcia", "Ceuta", "Melilla", "Canary Is."),
  poblacion = c(2701743, 1006193, 583904, 2188017, 661203, 319914, 1320586, 6714142, 2394918, 
                2046107, 1065424, 7739758, 5057353, 1172540, 8472403, 1511251, 84777, 86384, 2252465)
)

frecuencia_discriminacion <- frecuencia_discriminacion %>%
  left_join(poblacion_comunidades, by = "region")

frecuencia_discriminacion <- frecuencia_discriminacion %>%
  mutate(tasa_discriminacion = (casos / poblacion) * 100000)

map_data <- spain_map %>%
  left_join(frecuencia_discriminacion, by = c("region" = "region"))

map_data <- map_data %>%
  mutate(label = paste(name, "<br>Tasa de discriminación:", round(tasa_discriminacion, 2), "casos por 100,000 habitantes"))


p3 <- ggplot(data = map_data) +
  geom_sf(aes(fill = tasa_discriminacion, text=label), color = "white") +
  scale_fill_gradient(low = "yellow", high = "red", na.value = "grey50") +
  labs(fill = "Nivel de discriminación") +
  theme_void()

p3_interactive<-ggplotly(p3, tooltip = "text")
p3_interactive <- p3_interactive %>% layout(
  autosize=TRUE
)

p3_interactive

```




### Discriminación vs. Historia laboral

```{r fig.width=16, fig.height=10}
datos_filtrados2 <- datos%>%
  filter(pdjobev %in% c(1, 2))

discriminaciones_relevantes <- c("Edad", "Discapacidad", "Etnia", "Género", "Lengua", "Nacionalidad", "Raza", "Sexualidad")
datos_filtrados2 <- datos_filtrados2 %>%
  mutate(discriminacion_total = ifelse(discrimination %in% discriminaciones_relevantes, "Sí", "No"))

# Agrupar por pdjobev y discriminacion_total y contar los casos
datos_agg2 <- datos_filtrados2 %>%
  group_by(pdjobev, discriminacion_total) %>%
  summarise(count = n()) %>%
  ungroup()

# Calcular los porcentajes
datos_agg2 <- datos_agg2 %>%
  group_by(pdjobev) %>%
  mutate(percentage = count / sum(count) * 100)

# Crear el gráfico
p2 <- ggplot(datos_agg2, aes(
    y = factor(pdjobev, levels = c(1, 2), labels = c("Sí", "No")), 
    x = percentage, 
    fill = discriminacion_total, 
    text = paste("Porcentaje:", round(percentage, 2), "%<br>", "Casos:", count)
  )) +
  geom_bar(stat = "identity", position = "stack") +
  labs(y = "Alguna vez tuvo un trabajo remunerado", x = "Porcentaje de casos", fill = "Discriminación") +
  scale_x_continuous(labels = scales::percent_format(scale = 1)) +
  scale_fill_manual(values = c("Sí" = "dodgerblue", "No" = "lightsteelblue")) +
  theme_minimal() 

# Convertir el gráfico de ggplot2 a plotly para interactividad
ggplotly(p2, tooltip = "text")
```


Tablas {data-icon=fa-table}
=========================================

```{r}
datatable(datos,
          caption= 'Datos Discriminación 2002-2023',
          rownames= T,
          filter= 'top',
          options= list(pageLength=25))
```


